### ISSUE TITLE
Add bower support & more

### ISSUE THREAD

**Issue by redaxmedia** [jasonzissman/TimeMe.js#1]
- [x] Please add bower support to your repository and register the project
- [x] Please add " ifvisible.js" as dependency, never put third party libs into your repository.
- [x] Please create a tag
- [x] Please correct the typo in TImeMe.js to TimeMe.js
- [x] Update the API from <code>clear*</code> to <code>reset*</code> inside the README.md 

Thanks

**Comment by jasonzissman** [comment]
Thanks for the pointers.  I'll be taking care of all of these later this weekend!

**Comment by redaxmedia** [comment]
I also suggest to use type safe === in your if :-)

**Comment by redaxmedia** [comment]
clearRecordedPageTime is still in README.md ...

**Comment by jasonzissman** [comment]
As always, thanks for the tips!  I am going to do some Bower investigation now, and will hopefully get around to properly introducing it (and tagging TimeMe, and reference ifvisible) today!

**Comment by jasonzissman** [comment]
I've added Bower Support and registered it with Bower.  I thank you for the help, it is much appreciated!  If you notice anything still wrong (very likely - I am new to Bower), please let me know!

**Comment by redaxmedia** [comment]
Don't be shy with your 0.0.0 tag ... it is worth the 1.0.0 :-)
