### ISSUE TITLE
Stop timer when page is not visible

### ISSUE THREAD

**Issue by rubenvandeven** [jasonzissman/TimeMe.js#18]
I run startTimer from a setInterval(); This is not detected, so it still starts counting while the page is not visible.
I think it would be best to immediately stop the timer when a startTimer() is triggered while being invisible. This will create an duration of '0', as would probably be sensible:

``` javascript
startTimer: function () {
    var pageName = TimeMe.currentPageName;
    if (TimeMe.startStopTimes[pageName] === undefined) {
        TimeMe.startStopTimes[pageName] = [];
    } else {
        var arrayOfTimes = TimeMe.startStopTimes[pageName];
        var latestStartStopEntry = arrayOfTimes[arrayOfTimes.length - 1];
        if (latestStartStopEntry !== undefined && latestStartStopEntry.stopTime === undefined) {
            // Can't start new timer until previous finishes.
            return;
        }
    }
    TimeMe.startStopTimes[pageName].push({
        "startTime": new Date(),
        "stopTime": undefined
    });

    // immediately stop timer, if start is requested while page is out of focus:
    if(TimeMe.getIfVisibleHandle().now() == false)
    {
        TimeMe.stopTimer();
    }
},
```

**Comment by redaxmedia** [comment]
Your feature request is not invalid, because the control and behaviour belongs to the consuming project or library.

If someone likes to track the duration of losing focus while using a clickout button and returning back to the website?

**Comment by jasonzissman** [comment]
I apologize for taking so long to get back to this.  I agree with both of your assessments.  I'll include this shortly.

**Comment by jasonzissman** [comment]
I have merged the suggested changes into master.  Please let me know if I can help with anything else.

**Comment by redaxmedia** [comment]
Why did you ignore my comment and erged the pull request without a discussion? What if someone likes to track a duration from the event pagehide to pageshow? This pull requests makes the library useless for that usecase and maby others.

**Comment by jasonzissman** [comment]
So I've had some time to reflect on the original issue some more.  I think Redaxmedia is right - the calling application should make the decision on whether they really want to start the timer or not.   At a minimum the calling application could perform the exact same conditional check (TimeMe.getIfVisibleHandle().now() == false) to make the decision if appropriate. 

For now I will revert the changes.  I will keep this issue open in the mean time in case we need to continue the discussion or if someone provides counterpoints.  Sorry for the back-tracking!

**Comment by redaxmedia** [comment]
Haha, somethings it needs a year to change a opinion. Great move!
