### ISSUE TITLE
What does the user see?

### ISSUE THREAD

**Issue by dsernst** [jasonzissman/TimeMe.js#19]
What are the implications of this for the user? What will they see? 

- What does the network traffic look like? How often is it sent? How large are the payloads? What urls will be hit?

**Comment by jasonzissman** [comment]
Hi David!  Those questions all depend on how you use TimeMe.  By itself, TimeMe has no implications for the user, no implications for network traffic, no implications for payload sizes, etc.  The only thing TimeMe does is record how long a user interacts with your page.  Its logic is contained 100% in javascript and does not, by itself, display to the user or report to a server.  

When you use TimeMe.js, it is your responsibility to display the time to the user, or send it to your server in whatever payload you prefer.

Please let me know if I can help with anything!
