### ISSUE TITLE
Inittialize after reset causes failure 

### ISSUE THREAD

**Issue by redaxmedia** [jasonzissman/TimeMe.js#2]
Try this:

<pre>
TimeMe.setCurrentPageName('test');
TimeMe.initialize();
TimeMe.resetRecordedPageTime('test');

TimeMe.setCurrentPageName('test');
TimeMe.initialize();
</pre>

is causing a type error:

<pre>TypeError: arrayOfTimes[(arrayOfTimes.length - 1)] is undefined</pre>

**Comment by jasonzissman** [comment]
Great catch.  I put in a commit to fix the issue.

**Comment by redaxmedia** [comment]
Thanks for the fix
