### ISSUE TITLE
License Confusion

### ISSUE THREAD

**Issue by NeonMonk** [jasonzissman/TimeMe.js#24]
Bit confused about the license you've chosen to publish this under.

Is it Apache License, as the attached license file, or is it MIT as the bower.json file claims?

**Comment by jasonzissman** [comment]
Excellent catch.  I understand the MIT license to be more permissive, so I will lean towards that.  I'll put out a pull request to change the license to MIT.  In the meantime - do you have any opinion on which license type would be more useful for you?

**Comment by jasonzissman** [comment]
PR #25 created.

**Comment by NeonMonk** [comment]
Thank you for your quick response :)

MIT license is of course always preferred as the more permissive license. Personally in my case they're both perfectly fine.

Noting the simplistic differences: 

https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)
https://tldrlegal.com/license/mit-license

MIT is marginally simpler for libraries.
