### ISSUE TITLE
doc is not defined

### ISSUE THREAD

**Issue by thomasdavis** [jasonzissman/TimeMe.js#36]
You can view the error here

https://my.trackjs.com/shared/NmI1YThiYzcxYzM3NDIwMzk0NWY2YjJkMTUxMDNjMjk#telemetry

Click on Stack Trace for more information

**Comment by 2wsx** [comment]
This moment I got the same error and found this comment here, already.
The bug is in line 290 in timeme.js
`} else if (typeof doc.mozHidden !== "undefined") {`
I think it must be:
`} else if (typeof document.mozHidden !== "undefined") {`

**Comment by jasonzissman** [comment]
Good catch, and very sorry for the late response. This has been fixed.
