### ISSUE TITLE
Demo link http://timemejs.com/ is broken

### ISSUE THREAD

**Issue by deeptibaghel** [jasonzissman/TimeMe.js#44]
Demo link  http://timemejs.com/  README.md is broken.

**Comment by knalbandianbrightgrove** [comment]
@deeptibaghel you can download the repository and open it locally

**Comment by Austio** [comment]
@knalbandianbrightgrove not just broken but redirected to an ad service, see #45

**Comment by jasonzissman** [comment]
Bad link removed. Thanks!
