### ISSUE TITLE
Disable Timeout

### ISSUE THREAD

**Issue by Candunc** [jasonzissman/TimeMe.js#5]
I've been playing around with TimeMe.js today, however it seems there is no way to disable a timeout. By default, the timeout appears to be 60 seconds, and any other numbers (0, -1, infinity) all seem to change the timeout to 0. I've also tried 2678400 seconds as well, although it seems to default to the 0 timeout.

**Comment by jasonzissman** [comment]
Great idea!  That was an oversight on my part - I didn't even think to include something like this.  I'll have it enabled shortly, probably so that -1 means 'no timeout'.

**Comment by jasonzissman** [comment]
I've added logic to disable the timeout and merged it into master.  The default is still 60 seconds unless otherwise specified, but providing a timeout of -1 will disable the idle timeout mechanism.  It seems to work!  Let me know if any other problems arise.

**Comment by Candunc** [comment]
Awesome, thank you!
