### ISSUE TITLE
Bug in your implementation Incorrect time tracked

### ISSUE THREAD

**Issue by slidenerd** [jasonzissman/TimeMe.js#61]
Firefox version 68.0.2 (64-bit)
Platform OSX High Sierra 0.13.6

**How to reproduce**

1. Set idletimeout to -1 so that it immediately stops the moment the user stops
2. Move around the page, timer is running
3. Go to a different tab
4. Come back to our tab but dont move the mouse into the address bar or anywhere below the address bar
5. Timer still running

![bug](https://user-images.githubusercontent.com/5139030/63225322-07464880-c1ec-11e9-907f-55d6b9c891d5.gif)

**Comment by jasonzissman** [comment]
Reproduced, fixed, merged into master.
