### ISSUE TITLE
Timer stops counting when leaving page even though  trackWhenUserLeavesPage = false

### ISSUE THREAD

**Issue by proniotov** [jasonzissman/TimeMe.js#70]
I want to just know the time a user completely spends on the site even if the user is afk or not...
i found this and tried configuring it so i could get the time a user has my site up for.
When i ran it with the `trackWhenUserGoesIdle`  and `trackWhenUserLeavesPage` set to false, it continued to stop the timer...
Pls tell me if theres a way i can fix it in my code or if this is a problem from the developers...
heres the code:
```html
<script src="../timeme.min.js"></script>
	<script type="text/javascript">
		TimeMe.initialize({
      trackWhenUserGoesIdle: false,
      trackWhenUserLeavesPage: false,
		});
```

**Comment by DanielMalmgren** [comment]
Are you sure you are on the latest version? I had the exact same problem and then I realized that my js file was too old, after downloading the latest one this worked for me. This option was added 18 october 2020.

**Comment by proniotov** [comment]
Sry for the late response, apparently my file was outdated even though I had found this the day I opened the issue lol
Thanks!
