### ISSUE TITLE
ifvisible is not defined

### ISSUE THREAD

**Issue by redaxmedia** [jasonzissman/TimeMe.js#9]
Please confirm that ifvisible.js was loaded before you using it. Maby you pass it via the closure:

<pre>
(function (ifvisible) {

if (typeof ifvisible === 'object') {
}

})(this.ifvisible);</pre>

**Comment by jasonzissman** [comment]
Good idea!  Do you have any recommendations on what to do if ifvisible is not defined?  I could include a console.log() message, but I don't know if people typically want log messages (even during exceptional cases like this) to be written to the console.  Perhaps I should throw an exception instead?

**Comment by redaxmedia** [comment]
I suggest to write an internal method <code>ifVisible</code> for the external library like:

<pre>
(function (ifvisible) {
..
..
..
getVisible: function() {
    if (typeof ifvisible === 'object') {
      //return the ifvisible object
    }
    else {
      throw 'error, warning or whatever you think';
    }
}
..
..
})(this.ifvisible);
</pre>

Later on I suggest to use this internal method / wrapper inside a <code>listen</code> method that is made for the event handling... ifvisible.on(...)

<pre>
listen: function () {
..
TimeMe.getVisible.on('...')
..
}
</pre>

Finally you let the user start the listen method or add it to your init method.

**Comment by jasonzissman** [comment]
I put together a pull request: https://github.com/jasonzissman/TimeMe.js/pull/11.  Care to take a look at it? Thanks as always for the help.

**Comment by redaxmedia** [comment]
Looks good

**Comment by redaxmedia** [comment]
Please create a new tag like 1.1.0

**Comment by jasonzissman** [comment]
Done!
